name: Terraform CI

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string

      git_diff_relative:
        required: false
        type: string
        default: ''
      tflint_version:
        required: false
        type: string
        default: 0.34.1
      tflint_hcl_path:
        required: false
        type: string
        default: ./.tflint.hcl

jobs:
  fmt:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - run: terraform fmt -recursive -check -diff

  set-matrix:
    runs-on: ubuntu-20.04

    outputs:
      dirs: ${{ steps.set-matrix.outputs.dirs }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Detect dirs containing created or updated *.tf
        id: set-matrix
        run: |
          dirs=$(git diff origin/main...HEAD --diff-filter=d --name-only --relative=${{ inputs.git_diff_relative }} | grep -E "\.tf$" | xargs -I {} dirname {} | uniq | jq -R -s -c 'split("\n")[:-1]')
          echo $dirs
          echo "::set-output name=dirs::${dirs}"

  tflint:
    needs: set-matrix

    if: needs.set-matrix.outputs.dirs != '[]' && inputs.tflint_hcl_path

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        TF_DIR: ${{ fromJson(needs.set-matrix.outputs.dirs) }}

    steps:
      - uses: actions/checkout@v2

      - uses: terraform-linters/setup-tflint@7cf6558386ea02736c0a5edd3031f39c2dfeb206 #v1.1.0
        with:
          tflint_version: v${{ inputs.TFLINT_VERSION }}

      - name: Run tflint
        run: |
          tflint --init --config=${{ github.workspace }}/${{ inputs.tflint_hcl_path }}
          tflint --config=${{ github.workspace }}/${{ inputs.tflint_hcl_path }}
        working-directory: ${{ matrix.TF_DIR }}
