name: tflint all dirs

on:
  workflow_call:
    inputs:
      tf_root_dir:
        required: false
        type: string
        default: .
      tflint_version:
        required: false
        type: string
        default: latest
      own_tflint_hcl_exists:
        required: false
        type: boolean
        default: false
      tflint_hcl_path:
        required: false
        type: string
        default: .tflint.hcl

jobs:
  tflint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: terraform-linters/setup-tflint@7cf6558386ea02736c0a5edd3031f39c2dfeb206 #v1.1.0
        with:
          tflint_version: ${{ inputs.TFLINT_VERSION }}

      - name: Download ready-made .tflint.hcl
        if: ${{ !inputs.own_tflint_hcl_exists }}
        run: |
          curl -O https://raw.githubusercontent.com/shonansurvivors/github-actions-workflows/main/.tflint.hcl

      - name: Run tflint
        run: |
          tflint --init --config=${{ github.workspace }}/${{ inputs.tflint_hcl_path }}
          dirs=$(find ${{ inputs.tf_root_dir }} -type f -name '*.tf' -exec dirname {} \; | grep -v '\.terraform' | uniq)
          for dir in $dirs; do
            cd ${{ github.workspace }}/$dir
            tflint --force --config=${{ github.workspace }}/${{ inputs.tflint_hcl_path }}
          done
