name: tfsec all dirs

on:
  workflow_call:
    inputs:
      tf_root_dir:
        required: false
        type: string
        default: .

jobs:
  tfsec:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'

      - run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - run: tfsec --force-all-dirs --exclude-downloaded-modules
        working-directory: ${{ inputs.tf_root_dir }}
