name: tfsec all dirs

on:
  workflow_call:
    inputs:
      tf_root_dir:
        required: false
        type: string
        default: .

jobs:
  tfsec:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: Run tfsec
        run: |
          dirs=$(find ${{ inputs.tf_root_dir }} -type f -name '*.tf' -exec dirname {} \; | grep -v '\.terraform' | uniq)
          for dir in $dirs; do
            echo $dir
            cd ${{ github.workspace }}/$dir
            tfsec . --soft-fail
          done
